### ISSUE TITLE
Add support for yarn 2.0 Plug'n'Play feature

### ISSUE THREAD

**Issue by volkipp** [medikoo/ncjsm#5]
Since Yarn 2.0 is out with support for Plug'n'Play module resolution turned on by default, it would be great to see support for it within ncjsm. 

Related links: 
https://classic.yarnpkg.com/en/docs/pnp/
https://yarnpkg.com/advanced/pnpapi
https://github.com/serverless/serverless/issues/5634

**Comment by medikoo** [comment]
Thanks @volkipp for request, at this point it's hard for me to judge whether it's good direction for this package or not, as I'm not fully familiar with the idea.

I'll keep it open for now, once I get more accustomed and/or it'll become more mature (adapted) we'll settle on some solution.

**Comment by nkalinov** [comment]
+1 We also need this now as part of migrating our serverless projects into an Yarn2 PnP monorepo.

**Comment by nkalinov** [comment]
FYI I managed to workaround the issues for now. Instructions here: https://github.com/serverless/serverless/issues/5634#issuecomment-611401126

**Comment by medikoo** [comment]
@nkalinov I've checked on PNP, installed some project with `yarn --pnp` and it just doesn't work with Node.js. That seems actually expected as `node_modules` is not created, and Node.js cannot resolve dependencies.

I understand that it serves more bundlers and compilers, which need to be used to _build_ the project for Node.js (or other platform)? But it cannot be used for _pure_ Node.js projects with no transpilation involved. Correct?

**Comment by medikoo** [comment]
@volkipp great thanks for explanations.

Do you have link or maybe can provide short insight to why it was agreed and designed to work that way?

What troubles me specifically is that it derives from JS standard and Node.js API as it is now.

I assume that same effect could have been achieved by embracing [Import Maps](https://github.com/WICG/import-maps) and that effort could have been put into Node.js codebase directly to support them. Then naturally this will work on Node.js grounds.

`ncjsm` project technically generalizes NCJS resolution as defined in Node.js, and I find it controversial to bake-in support for some side solutions that move away from how things work in Node.js.

**Comment by JReinhold** [comment]
> Do you have link or maybe can provide short insight to why it was agreed and designed to work that way?

The Yarn docs have a good overview of the benefits of the PnP approach: https://yarnpkg.com/features/pnp

> I assume that same effect could have been achieved by embracing [Import Maps](https://github.com/WICG/import-maps) and that effort could have been put into Node.js codebase directly to support them. Then naturally this will work on Node.js grounds.

I don't know much about Import Maps, but AFAIK developing and getting features into Node.js is very time consuming, and can take years for everyone to agree on what to do, and then actually implement it. I believe Yarn PnP has been conceived also to show the Node.js community how stuff can improve, in an attempt to push the game forward. This is a rather big change, so it would make sense that if this was to be proposed to be implemented in Node.js, or at least something similar, it would first have to had been battle tested in large scale - which I believe is the point of adding it to Yarn first. That is just my personal assumption though.

npm has been working on something very similar to PnP called tink, however it seems like progress on that has been stalled ever since the great employment shuffle at npm Inc. 
https://medium.com/@Andrew_Mc/yarn-pnp-npm-tink-and-pnpm-oh-my-720d02221b4b
https://2019.jsconf.eu/kat-marchan/tink-a-next-generation-package-manager.html

**Comment by medikoo** [comment]
@JReinhold great thanks for explanations.

Idea of this project is to provide convenient utils around CommonJS modules handling as it works in Node.js.

At this point I'm not convinced to support any 3rd party solutions which do not aim to be a _natively_ supported _standard_ in Node.js directly.

In my understanding problem that Yarn PNP is trying to solve, can be solved on _standard_ grounds (e.g. via [Import Maps](https://github.com/WICG/import-maps)) and be implemented in to Node.js directly.

Yarn with PNP didn't take that route, which leaves me with feeling that it's just Yarn proprietary thing, and at least at this point I don't think any proprietary stuff should be supported here.

I'm going to close this issue now, but I remain open for any further feedback and further discussion on that matter.

**Comment by arcanis** [comment]
> Yarn with PNP didn't take that route, which leaves me with feeling that it's just Yarn proprietary thing, and at least at this point I don't think any proprietary stuff should be supported here.

Plug'n'Play has been designed as an open standard resolution strategy, and is supported by Yarn but also by pnpm. That it's not in Node by default is irrelevant, since many other resolutions exist without being "the default" - import maps themselves aren't supported natively, neither is the `module` field. Even ESM resolution has various flavors that are still being sorted out.

By contrast, most JS tools nowadays are conceived to be at least partially compatible with PnP (for instance Webpack, Jest, Husky, Gatsby, Next, Rollup, Parcel, ..., all have native support for it), and not recognizing its existence just makes it harder for your users to justify using Serverless, as they need to downgrade their performances in order to do so - and that's just for the sake of CLI plugins.

> In my understanding problem that Yarn PNP is trying to solve, can be solved on _standard_ grounds (e.g. via [Import Maps](https://github.com/WICG/import-maps)) and be implemented in to Node.js directly.

No, otherwise we would have done so 🙂 Existing proposals (or perhaps "competing proposals", as Import Maps weren't a thing back when PnP was first released) don't meet our criterias in terms of developer experience and semantics.
